version: '3.5'

services:
  spring:
    image: 'customer-service:latest'
    build:
      context: .
    container_name: spring
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/customerService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgreSQLpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_DB=customerService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgreSQLpass

  react-service:
    container_name: react-container
    build:
      context: ./cust-serv
      dockerfile: Dockerfile
    volumes:
      - .:/cust-serv/app
      - /cust-serv/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true